version: '3'
services:
  restaurant-db:
    image: mysql:8.0.33
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "restaurant_api"
    networks:
      - restaurant-net

  restaurant-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      MYSQL_HOST: "restaurant-db"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
      MYSQL_PORT: "3306"
    networks:
      - restaurant-net

networks:
  restaurant-net:
    driver: bridge
