apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: restaurant-api-docker
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: restaurant-db
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: ""
            - name: MYSQL_PORT
              value: "3306"
